language: php

notifications:
  on_success: never
  on_failure: change

php:
  - 5.3
  - 5.5
  - 5.6

env:
  - WP_VERSION=4.3 WP_MULTISITE=0
  - WP_VERSION=4.3 WP_MULTISITE=1
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
 
before_script:
  - composer install --no-interaction
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
   - vendor/bin/phpcs -n --report=emacs --standard=phpcs.ruleset.xml class-echo-js-lazy-load.php
   - phpunit
