language: php

notifications:
  on_success: never
  on_failure: change

services:
  - mysql

matrix:
  include:
    - php: 5.6
      dist: precise
      env: WP_VERSION=5.3 WP_MULTISITE=0
    - php: 7.2
      dist: trusty
      env: WP_VERSION=5.3 WP_MULTISITE=0
    - php: 7.4
      dist: xenial
      env: WP_VERSION=5.3 WP_MULTISITE=0
    - php: 5.6
      dist: precise
      env: WP_VERSION=5.3 WP_MULTISITE=1
    - php: 7.2
      dist: trusty
      env: WP_VERSION=5.3 WP_MULTISITE=1
    - php: 7.4
      dist: xenial
      env: WP_VERSION=5.3 WP_MULTISITE=1
    - php: 7.4
      dist: xenial
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 7.4
      dist: xenial
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - composer install --no-interaction
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
   - vendor/bin/phpcs -n --report=emacs --standard=phpcs.ruleset.xml class-echo-js-lazy-load.php
   - vendor/bin/phpunit
